__name__ = "tangl"
__desc__ = "The abstract narrative graph lib for interactive stories"
__title__ = "Tangl"
__author__ = "Derek Merck"
__author_email__ = "derek.merck@gmail.com"
__url__ = "https://github.com/derekmerck/tangl"
__version__ = "3.2.0"
