__name__ = "tangl"
__desc__ = "The abstract narrative graph lib for interactive stories"
__title__ = "StoryTangl"
__author__ = "TanglDev"
__author_email__ = "tangldev@storytan.gl"
__url__ = "https://github.com/story/tangl"
__version__ = "3.4.0"
