"""Credential mechanics shared by games, assembly, and future transactions."""

from .assembly import (
    CREDENTIAL_ID_SLOT,
    CREDENTIAL_PACKET_SLOT,
    CredentialComponent,
    CredentialComponentToken,
    CredentialDefinition,
    CredentialPacketManager,
    default_credential_catalog,
    ensure_default_credential_definitions,
    materialize_packet,
)
from .domain import (
    COMMON_ALLIED_RESTRICTIONS,
    COMMON_HOSTILE_RESTRICTIONS,
    COMMON_LOCAL_RESTRICTIONS,
    CONTRABAND,
    DEFAULT_RESTRICTIONS,
    PURPOSES,
    ContrabandItem,
    CredentialDefect,
    CredentialDefectKind,
    CredentialStatus,
    CredentialToken,
    FailureClass,
    FailureMode,
    Indication,
    IndicationId,
    OriginId,
    Region,
    RestrictionLevel,
    RestrictionMap,
    RestrictionRule,
    Restrictions,
)

# Register the credential-owned default text presentation handlers.
from .presentation import (
    CredentialAttestationObservation,
    CredentialCardProjection,
    CredentialValidityObservation,
    CredentialVisibleObservation,
)
from .card_media import (
    credential_card_composition_spec,
    credential_card_portrait_spec,
    credential_card_text_spec,
)

__all__ = [
    "COMMON_ALLIED_RESTRICTIONS",
    "COMMON_HOSTILE_RESTRICTIONS",
    "COMMON_LOCAL_RESTRICTIONS",
    "CONTRABAND",
    "CREDENTIAL_ID_SLOT",
    "CREDENTIAL_PACKET_SLOT",
    "CredentialComponent",
    "CredentialComponentToken",
    "CredentialAttestationObservation",
    "CredentialCardProjection",
    "CredentialValidityObservation",
    "CredentialVisibleObservation",
    "credential_card_composition_spec",
    "credential_card_portrait_spec",
    "credential_card_text_spec",
    "CredentialDefinition",
    "CredentialPacketManager",
    "default_credential_catalog",
    "ensure_default_credential_definitions",
    "materialize_packet",
    "CredentialStatus",
    "CredentialDefect",
    "CredentialDefectKind",
    "CredentialToken",
    "ContrabandItem",
    "DEFAULT_RESTRICTIONS",
    "FailureClass",
    "FailureMode",
    "Indication",
    "IndicationId",
    "OriginId",
    "PURPOSES",
    "Region",
    "RestrictionLevel",
    "RestrictionMap",
    "RestrictionRule",
    "Restrictions",
]
