from __future__ import annotations
from typing import Literal, Optional, TYPE_CHECKING, Self
from base64 import b64encode
from uuid import UUID

from pydantic import Field, field_serializer, BaseModel, AnyUrl, model_validator, PrivateAttr

from tangl.type_hints import Pathlike
# from tangl.media import MediaRecord
from tangl.core.fragment import ContentFragment, ControlFragment
# from tangl.media.enums import MediaRole
from .media_presentation_hints import MediaPresentationHints

if TYPE_CHECKING:
    from tangl.core.data_resources import ResourceRegistry, ResourceInventoryTag as RIT

MediaFragmentType = Literal['media', 'image', 'vo', 'music', 'sfx', 'anim', 'mov']
DataContentFormatType = Literal['url', 'data', 'xml', 'json']

class MediaFragment(ContentFragment, extra='allow'):
    """
    This is the final data type that is produced by the service layer from a media resource generated by the domain layer.

    Attributes:
      - uid (UUID): Unique identifier of the generating story entity.
      - media_role (MediaRole): Intended use, e.g., `narrative_im`
      - url (url): Path to resource for client.
      - data (str): xml or base64 encoded data.
      - record (RIT): Resource inventory tag to be processed into data or url by the service layer
      - text (str): Rendered content text (caption, label, lyric, etc.)

    Only one of url or data may be provided.
    """
    fragment_type: MediaFragmentType = Field("media", alias='type')
    content: Pathlike | bytes | str
    content_format: DataContentFormatType = Field(..., alias='format')
    media_hints: Optional[MediaPresentationHints] = None

    # media_role: MediaRole

    # These may be passed in directly from a ref with external or embedded data
    url: Optional[AnyUrl] = None  # either url or data
    data: Optional[str] = None    # svg or base64 encoded

    @field_serializer("content")
    def _encode_data_content(self, content):
        if self.content_format == "data":
            return b64encode(content)
        return str(content)

    #: Processed by service layer and discarded
    media_record_id: Optional[UUID] = Field(None, exclude=True)

    @property
    def media_record(self) -> RIT:
        on_get_media.execute(self.media_record_id)

    # @classmethod
    # def from_media_record(cls, media_record: 'MediaRecord', **kwargs) -> 'MediaFragment':
    #     ...

    # @model_validator(mode='after')
    # def _check_exactly_one(self) -> Self:
    #     if not any([self.url, self.data, self._record]) or all([self.url, self.data, self._record]):
    #         raise ValueError("Exactly one of `url`, `data`, or `record` must be provided")
    #     return self


