"""Read `trades.d2` and answer the questions an author has about it.

    python -m red_paperclip              # check it, and report the ends
    python -m red_paperclip --mermaid    # draw it
    python -m red_paperclip --asp GOAL   # emit it as an ASP planning world

The first two need nothing but this package. The third writes the archived
solver proof of concept's vocabulary (`action/1`, `pre/2`, `add/2`, `del/2`,
`init/1`, `goal/1`), so `engine.lp` from that proposal can plan over this world
unmodified — see issue #396. Holding one thing and spending a trader are both
linear resources, which is the shape that formalism is for, and travel is
modelled as it is played, so a minimal plan counts journeys as well as trades.
"""

from __future__ import annotations

from pathlib import Path
import sys

import yaml

from .trade_graph import START_ITEM, TradeGraph, Trader


SCRIPT_FILE = Path(__file__).resolve().parent.parent / "script.yaml"


def map_hub(path: Path | None = None) -> str:
    """Return the label of the location that owns the map plate.

    Read from `script.yaml` rather than named here, because the ASP model
    travels through it: a hub renamed in the world and not here would emit a
    model of a district that does not exist, and nothing would say so.
    """
    script = yaml.safe_load((path or SCRIPT_FILE).read_text(encoding="utf-8"))
    for scene in script["scenes"].values():
        for label, block in scene["blocks"].items():
            if isinstance(block, dict) and "map" in block:
                return label
    raise SystemExit("no location in script.yaml owns a map plate")


def report(trades: TradeGraph) -> str:
    """Return the author's-eye view: what ends the story, and how far away."""
    routes = trades.routes()
    lines = [
        f"{len(trades.items)} items, {len(trades.traders)} traders, "
        f"{len(trades.hubs())} hubs: {', '.join(trades.hubs())}",
    ]
    unreachable = sorted(set(trades.items) - set(routes))
    lines.append(
        "unreachable: " + (", ".join(unreachable) if unreachable else "nothing")
    )
    stranded = trades.dead_ends()
    lines.append(
        "dead ends: "
        + (
            ", ".join(stranded)
            if stranded
            else "none (every stop is on an item nobody trades for)"
        )
    )
    lines.append("")
    lines.append("ends the story:")
    for item in sorted(trades.endings(), key=lambda i: len(routes.get(i.label, []))):
        route = routes.get(item.label)
        if route is None:
            lines.append(f"  {item.label:20s} unreachable")
            continue
        hops = " -> ".join(trader.label for trader in route)
        lines.append(f"  {item.label:20s} {len(route)} trades: {hops}")
    return "\n".join(lines)


def mermaid(trades: TradeGraph) -> str:
    """Return the trade graph as a mermaid flowchart, one node per item."""
    lines = ["flowchart LR"]
    for item in trades.items.values():
        shape = "([%s])" if trades.is_terminal(item.label) else "[%s]"
        lines.append(f"  {item.label}{shape % item.name}")
    for trader in trades.traders.values():
        for held in trader.accepts:
            lines.append(
                f"  {held} -->|{trader.short_name} @ {trader.hub}| {trader.offers}"
            )
    return "\n".join(lines)


def _trade_action(trader: Trader, held: str) -> str:
    name = f"trade_{trader.label}_{held}"
    return "\n".join(
        [
            f"action({name}).",
            f"  pre({name}, at({trader.hub})).",
            f"  pre({name}, holding({held})).",
            f"  pre({name}, unspent({trader.label})).",
            f"  del({name}, holding({held})).",
            f"  del({name}, unspent({trader.label})).",
            f"  add({name}, holding({trader.offers})).",
        ]
    )


def _travel_action(source: str, target: str) -> str:
    name = f"go_{source}_{target}"
    return "\n".join(
        [
            f"action({name}).",
            f"  pre({name}, at({source})).",
            f"  del({name}, at({source})).",
            f"  add({name}, at({target})).",
        ]
    )


def asp(trades: TradeGraph, goal: str) -> str:
    """Return the world as ASP facts for the archived solver engine."""
    if goal not in trades.items:
        raise SystemExit(f"no such item to aim at: {goal!r}")
    hub = map_hub()
    blocks = [
        "%% generated by `python -m red_paperclip --asp` from trades.d2.",
        "%% Pairs with engine.lp from the formal solver proof of concept (#396).",
        "",
        f"init(holding({START_ITEM})).",
        f"init(at({hub})).",
        *(f"init(unspent({label}))." for label in trades.traders),
        "",
        *(
            block
            for trader in trades.traders.values()
            for block in (_trade_action(trader, held) for held in trader.accepts)
        ),
        *(
            block
            for spoke in trades.hubs()
            for block in (
                _travel_action(hub, spoke),
                _travel_action(spoke, hub),
            )
        ),
        f"goal(holding({goal})).",
    ]
    return "\n".join(blocks)


def main(argv: list[str]) -> int:
    """Run one report over the world's trade file."""
    trades = TradeGraph.load()
    if "--mermaid" in argv:
        print(mermaid(trades))
    elif "--asp" in argv:
        index = argv.index("--asp")
        goal = argv[index + 1] if len(argv) > index + 1 else "ostrich_share"
        print(asp(trades, goal))
    else:
        print(report(trades))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
