from __future__ import annotations

import pydantic
from typing import Optional

from pydantic import AnyUrl, model_validator

from tangl.entity import BaseJournalItem
from tangl.resource_registry import ResourceInventoryTag as RIT
from .enums import MediaRole

class JournalMediaItem(BaseJournalItem):
    """
    This is the final data type that is produced by the service layer from a media resource generated by the domain layer.

    Attributes:
      - uid (UUID): Unique identifier of the generating story entity.
      - media_role (MediaRole): Intended use, e.g., `narrative_im`
      - url (url): Path to resource for client.
      - data (str): xml or base64 encoded data.
      - text (str): Rendered content text.
      - rit (RIT): Resource inventory tag to be processed into data or url by the service layer

    Only one of url or data may be provided.
    """
    media_role: MediaRole

    # These may be passed in directly from a ref with external or embedded data
    url: Optional[AnyUrl] = None  # either url or data
    data: Optional[str] = None    # svg or base64 encoded

    @model_validator(mode='after')
    def _check_exactly_one(self) -> JournalMediaItem:
        if not any([self.url, self.data, self._rit]) or all([self.url, self.data, self._rit]):
            raise ValueError("Exactly one of `url`, `data`, or `rit` must be provided")
        return self

    #: Processed by service layer and discarded
    _rit: Optional[RIT] = pydantic.PrivateAttr(None)

