# tangl.core.fragment.content_fragment.py
from typing import Optional, Any
from enum import Enum

from pydantic import Field

from tangl.core.record import Record
from .presentation_hints import PresentationHints


class ContentFragment(Record):
    """
    Specialized entity that provides the core schema for communicating content
    about the graph to a front-end.

    The journal is made up of ordered content fragments generated by structure nodes
    as they are traversed by the graph cursor.

    - ContentFragments and InfoFragments are _content_ objects in the fragment stream
    - GroupFragments and UpdateFragments are _control_ objects in the fragment stream
    - MediaFragments and DiscourseFragments are application-specific constructs
      that have their own special rules for how their content field is represented.

    JournalFragments are Nodes on the graph, they are connected to their
    originating structure or resource nodes by 'blame' edges for auditing.

    Edges between content fragments are implicit in sequence since the journal is
    strictly linear and monotonic in sequence.

    Attributes:
    - fragment_type: General type of fragment, i.e., text, media, kv, runtime, used
      for automatically inferring fragment type from data.
    - label (str): Optional name/key for the fragment
    - content (str): Optional value/text/media for the fragment
    - content_format: Instruction for how to parse content field, ie, markdown or encoded data
    """
    # fragments are immutable once created; should inherit this, though
    # model_config = ConfigDict(frozen=True)

    # red, output, linked within by red, without by yellow
    record_type: str | Enum = Field('content_fragment', alias='type')
    # intent for fragment, e.g., 'content', 'update', 'group', 'media', etc.
    content: Any
    content_format: Optional[str] = Field(None, alias='format')
    # seq and mime-type are added in the service layer, when the fragment is serialized into a dto.
    presentation_hints: Optional[PresentationHints] = Field(None, alias='hints')

